# Generated by Django 3.1.3 on 2020-11-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20201115_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='emall',
            new_name='email',
        ),
    ]
