# Generated by Django 3.1.3 on 2020-11-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20201125_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_usa',
            new_name='fees_in_usa',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_world',
            new_name='fees_in_world',
        ),
    ]
